CREATE TABLE Users
(
    Id INTEGER PRIMARY KEY,
    Username TEXT UNIQUE NOT NULL,
    PasswordHash TEXT NOT NULL
);

CREATE TABLE Recipes
(
    Id INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    CreatorId INTEGER NOT NULL,
    Instructions TEXT NOT NULL,
    Ingredients TEXT NOT NULL,

    FOREIGN KEY (CreatorId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE Tags
(
    Id INTEGER PRIMARY KEY,
    Name TEXT NOT NULL
);

CREATE TABLE TagJoin
(
    RecipeId INTEGER NOT NULL,
    TagId INTEGER NOT NULL,

    FOREIGN KEY (RecipeId) REFERENCES Recipes(Id) ON DELETE CASCADE,
    FOREIGN KEY (TagId) REFERENCES Tags(Id) ON DELETE CASCADE
);

CREATE TABLE Reviews
(
    RecipeId INTEGER NOT NULL,
    ReviewerId INTEGER NOT NULL,
    Rating INTEGER NOT NULL,
    Comment TEXT,

    FOREIGN KEY (RecipeId) REFERENCES Recipes(Id) ON DELETE CASCADE,
    FOREIGN KEY (ReviewerId) REFERENCES Users(Id) ON DELETE CASCADE
);